global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus-go'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'bitmagnet'
    static_configs:
      - targets: ['host.docker.internal:3333']
  - job_name: 'video-crawler'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: "node_your_mac"
    static_configs:
      - targets: ['host.docker.internal:9100']
